server:
  port: 8070

spring:
  application:
    name: Cliente

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
      
holamundo:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule